name: 'server deploy monitoring'
description: 'Monitor build time, optionally health-check a URL, and report success/failure via webhook'
author: 'ghkdqhrbals'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  webhook_url:
    description: 'Webhook URL to receive a JSON report (optional)'
    required: false
  health_check_url:
    description: 'URL to health-check on end (optional)'
    required: false
  health_wait_seconds:
    description: 'Optional: wait up to N seconds for health_check_url to return HTTP 200 (0 = no wait)'
    required: false
    default: '0'
  project_name:
    description: 'Project name for reporting'
    required: false
    default: 'unknown'
  action:
    description: 'Action to perform: start | end'
    required: true
  job_status:
    description: 'Job status string (recommended: pass the workflow job status, e.g. job.status)'
    required: false

outputs:
  build_time_ms:
    description: 'Build time in milliseconds (only set when action=end)'
    value: ${{ steps.end.outputs.build_time_ms }}
  build_status:
    description: 'Build status (success|failure|cancelled|unknown) (only set when action=end)'
    value: ${{ steps.end.outputs.build_status }}
  health_status:
    description: 'Health check status (ok|fail|skipped) (only set when action=end)'
    value: ${{ steps.end.outputs.health_status }}
  health_http_status:
    description: 'Health check HTTP status code (or skipped)'
    value: ${{ steps.end.outputs.health_http_status }}
  health_latency_ms:
    description: 'Health check latency in ms (or skipped/unknown)'
    value: ${{ steps.end.outputs.health_latency_ms }}

runs:
  using: 'composite'
  steps:
    - name: Start build monitoring
      id: start
      if: ${{ inputs.action == 'start' }}
      shell: bash
      run: |
        set -euo pipefail
        py=python3
        command -v python3 >/dev/null 2>&1 || py=python
        "$py" "${GITHUB_ACTION_PATH}/build_monitor.py" start --project-name "${{ inputs.project_name }}"

    - name: End build monitoring and send report
      id: end
      if: ${{ inputs.action == 'end' }}
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook_url }}
        HEALTH_CHECK_URL: ${{ inputs.health_check_url }}
        HEALTH_WAIT_SECONDS: ${{ inputs.health_wait_seconds }}
        INPUT_PROJECT_NAME: ${{ inputs.project_name }}
        INPUT_JOB_STATUS: ${{ inputs.job_status }}
      run: |
        set -euo pipefail
        py=python3
        command -v python3 >/dev/null 2>&1 || py=python
        "$py" "${GITHUB_ACTION_PATH}/build_monitor.py" end \
          --project-name "${INPUT_PROJECT_NAME:-unknown}" \
          --job-status "${INPUT_JOB_STATUS:-unknown}" \
          --webhook-url "${WEBHOOK_URL:-}" \
          --health-check-url "${HEALTH_CHECK_URL:-}" \
          --health-wait-seconds "${HEALTH_WAIT_SECONDS:-0}"
